// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhlybrzieiygmmmsbjqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1obHlicnppZWl5Z21tbXNianFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMjg5NjUsImV4cCI6MjA3MTcwNDk2NX0.f8WJ1fsA2l3AdA75MJ5no1IaOqHssVJcJYXCa6y1V1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});